---
from: Earo Wang
fromqualifications: B.Comm.(Hons)
fromtitle: PhD candidate
fromWWW: earo.me
fromemail: earo.wang@monash.edu
fromphone: +61 4 4919 1031
fromsignature: signature.png
toname: Editor
toaddress: Journal of Computational and Graphical Statistics
opening: Dear Dr McCormick,
closing: Sincerely
spacing: 1.4
output: MonashEBSTemplates::letter
---

Please consider our manuscript titled, "Calendar-based graphics for visualizing people's daily schedules," for publication in the Journal of Computational and Graphical Statistics.

This paper provides new graphical methods for organizing and visualizing temporal data, collected at sub-daily resolutions, into a calendar layout. It is useful to provide insights into people's daily schedules relative to events such as work days, weekends, holidays, and special events, based on calendar layouts. The calendar format is created using linear algebra, to restructure data, that can then be piped into ggplot2's plotting routines. Many options and variants are supported to make it broadly applicable. The methods are implemented in R package **sugrrants**, which is on CRAN. The paper is written in RMarkdown, which contains the R code to reproduce the results.

An early version of the paper won the 2018 ASA Statistical Graphics Section best student paper. We submitted that paper to the Journal of Statistical Software in September 2017. It took 12 months to received a review, and the decision was to reject without substantial feedback, other than a lack of examples. For this reason, we have added an additional contemporary data example of smart meter energy usage from several Melbourne households, to supplement the example of Melbourne pedestrian traffic. Because of the treatment by JSS, we also request that this paper is not handled by AE Paul Murrell. 

We believe that this manuscript is a good fit for the Journal of Computational and Graphical Statistics, because it provides new graphics methodology. Because the software has already received considerable attention, we expect that the work will be of interest to readers of the journal.
